### ISSUE TITLE
how to..

### ISSUE THREAD

**Issue by fachos** [adde88/reghack-openwrt#1]
hi.. where to put this reghack folder with your openwrt-pineapple-nano build? no luck so far... 

include/toplevel.mk:181: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by adde88** [comment]
You can simply create a folder structured like this: 'packages/net/reghack'
The Makefile in this repo, and all other files should be put inside that folder.

Here's a one-liner that should fix it for you:
```
cd packages/net/; git clone git@github.com:adde88/reghack-openwrt reghack;cd ../../
```
